### ISSUE TITLE
Wrong year of publication in list of works by proofreader

### ISSUE THREAD

**Issue by Glottotopia** [langsci/hallOfFame#1]
The year of publication in the list of  works a given proofreader has read is sometimes incorrect. 
![Screenshot_2023-11-16_11-07-11](https://github.com/langsci/hallOfFame/assets/1553576/d1cfd73d-6633-4491-a919-97e13aaff754)

Here, we see the year "2021", but the correct year is "2023"

**Comment by CFanselow** [comment]
Fixed.

**Comment by CFanselow** [comment]
Fixed by selecting latest version of the publication.
